### ISSUE TITLE
Could not load ini file! Config file not found: "$XDG_CONFIG_DIR/mopidy/mopidy.conf".

### ISSUE THREAD

**Issue by gerroon** [akatrevorjay/docker-mopidy-extras#5]
Whenever I try to change settings this is what I get :(

```
INFO     {"error": "Could not load ini file! Config file not found: \"$XDG_CONFIG_DIR/mopidy/mopidy.conf\". <class 'configobj.ConfigObjError'> <type 'exceptions.IOError'>"}
ERROR    Uncaught exception GET /material-webclient/wifi (172.17.0.1)
HTTPServerRequest(protocol='http', host='localhost:4680', method='GET', uri='/material-webclient/wifi', version='HTTP/1.1', remote_ip='172.17.0.1', headers={'Accept-Language': 'en-US,en;q=0.9', 'Accept-Encoding': 'gzip, deflate, br', 'Host': 'localhost:4680', 'Accept': 'application/json, text/plain, */*', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36', 'Dnt': '1', 'Connection': 'keep-alive', 'Referer': 'http://localhost:4680/material-webclient/'})
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1467, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_material_webclient/__init__.py", line 58, in get
    cells = Cell.all('wlan0')
  File "/usr/local/lib/python2.7/dist-packages/wifi/scan.py", line 39, in all
    stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
ERROR    500 GET /material-webclient/wifi (172.17.0.1) 8.18ms
ERROR    Could not load ini file! Config file not found: "$XDG_CONFIG_DIR/mopidy/mopidy.conf".
ERROR    Could not load ini file! Config file not found: "$XDG_CONFIG_DIR/mopidy/mopidy.conf".

```

**Comment by gerroon** [comment]
Btw it exists see

```
ls -alh $XDG_CONFIG_DIR/mopidy/mopidy.conf

-rwxr-xr-x 1 USER USER 6.0K Jun 20 22:24 /DATA/USER/.config/mopidy/mopidy.conf

```

**Comment by jacekpaszkowski** [comment]
Hi, i have the same error, could you please help with this issiue?
